// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistory(arg1) {
  return window['go']['backend']['App']['AddHistory'](arg1);
}

export function BrowseDir() {
  return window['go']['backend']['App']['BrowseDir']();
}

export function CancelDownload(arg1) {
  return window['go']['backend']['App']['CancelDownload'](arg1);
}

export function ClearHistory() {
  return window['go']['backend']['App']['ClearHistory']();
}

export function FetchVariants(arg1, arg2) {
  return window['go']['backend']['App']['FetchVariants'](arg1, arg2);
}

export function GetHistory() {
  return window['go']['backend']['App']['GetHistory']();
}

export function GetSettings() {
  return window['go']['backend']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['backend']['App']['GetVersion']();
}

export function HasFFmpeg() {
  return window['go']['backend']['App']['HasFFmpeg']();
}

export function Minimize() {
  return window['go']['backend']['App']['Minimize']();
}

export function PauseDownload(arg1) {
  return window['go']['backend']['App']['PauseDownload'](arg1);
}

export function Quit() {
  return window['go']['backend']['App']['Quit']();
}

export function RemoveHistory(arg1) {
  return window['go']['backend']['App']['RemoveHistory'](arg1);
}

export function ResumeDownload(arg1) {
  return window['go']['backend']['App']['ResumeDownload'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['backend']['App']['SaveSettings'](arg1);
}

export function ShowInFolder(arg1) {
  return window['go']['backend']['App']['ShowInFolder'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['backend']['App']['StartDownload'](arg1);
}

export function ToggleMaximize() {
  return window['go']['backend']['App']['ToggleMaximize']();
}
