// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddHistory(arg1:backend.HistoryItem):Promise<number>;

export function BrowseDir():Promise<string>;

export function CancelDownload(arg1:number):Promise<void>;

export function ClearHistory():Promise<void>;

export function FetchVariants(arg1:string,arg2:backend.ProxyConfig):Promise<Array<backend.Variant>>;

export function GetHistory():Promise<Array<backend.HistoryItem>>;

export function GetSettings():Promise<backend.Settings>;

export function GetVersion():Promise<string>;

export function HasFFmpeg():Promise<boolean>;

export function Minimize():Promise<void>;

export function PauseDownload(arg1:number):Promise<void>;

export function Quit():Promise<void>;

export function ResumeDownload(arg1:number):Promise<void>;

export function SaveSettings(arg1:backend.Settings):Promise<void>;

export function ShowInFolder(arg1:string):Promise<void>;

export function StartDownload(arg1:backend.DownloadRequest):Promise<number>;

export function ToggleMaximize():Promise<void>;
